export const PADDING_HORIZONTAL = 16;
export const PADDING_VERTICAL = 5;

export const MARGIN_HORIZONTAL = PADDING_HORIZONTAL;
export const MARGIN_VERTICAL = PADDING_VERTICAL;

export const BORDER_RADIUS = 10;
